import type { ReactNode } from "react"
import type { Metadata } from "next"
import { headers } from "next/headers"
import "./globals.css"
import "./visual-premium.css"
import "./locale-fixes.css"
import "./admin/admin.css"
import "./mobile-hardening.css"
import "./contact-flow.css"
import "./performance-stability.css"
import "./render-stability.css"
import "./admin/mobile-admin.css"
import "./responsive-mobile.css"
import "./bees.css"
import "./hero-social.css"
const BOOT="try{var d=document.documentElement;d.className+=(d.className?' ':'')+'js-ready';window.addEventListener('load',function(){setTimeout(function(){if(window.BouzidMotion)return;var n=document.querySelectorAll('.reveal,.reveal-scale,.img-reveal,.split');for(var i=0;i<n.length;i++){n[i].className+=' is-in'}},1200)})}catch(e){}"
export const metadata:Metadata={metadataBase:new URL(process.env.NEXT_PUBLIC_SITE_URL||"https://bouzid.com"),icons:{icon:"/assets/bouzid-logo.svg"},robots:{index:true,follow:true}}
export default async function RootLayout({children}:{children:ReactNode}){const h=await headers();const locale=h.get("x-bouzid-locale")||"ar";return <html lang={locale} dir={locale==="ar"?"rtl":"ltr"} suppressHydrationWarning><head><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta name="theme-color" content="#24140a"/><script dangerouslySetInnerHTML={{__html:BOOT}}/></head><body>{children}</body></html>}
